### PR TITLE
Permit umxRAM to accept lists in the dots argument

### PR DESCRIPTION
**Pull request by bwiernik**
Makes it possible pass lists of mxObjects to the function for more flexible model building.

### CODE REVIEW

**Comment by tbates** [comment]
OK, I see how this works now. Will accept the pull request

**Comment by bwiernik** [comment]
Thanks, yeah `unlist` applied to one or a list of MxObjects will return a list.

**Comment by tbates** [comment]
very R for unList to return a list :-)

**Comment by bwiernik** [comment]
I originally had a much more complicated series of logic to unlist the elements, then realized it was all redundant...

**Pull request merged**
