### PR TITLE
add fit more fit indices

### PR DESCRIPTION
**Pull request by bwiernik**
Everything compiles and builds now: 
https://github.com/tbates/umx/commit/8d08ce4be26eb670e383c59d31fcf97df33fc4e1

Sorry for the hassle.

### CODE REVIEW

**Comment by tbates** [comment]
Hi @bwiernik,
This PR had file conflicts, with two copies of the indices function, and <<< markers for the conflicts. 

It's tricky to fix these online, so I am just going to try and copy the code changes into my local copy. rather than do this pull (because of the conflicts).

**Comment by tbates** [comment]
Um, the help file example now emits a warning...

```SplusR
Warning message:
In if (!is.na(observed.means)) { :
  the condition has length > 1 and only the first element will be used
```
Are you seeing that? It can't be included while it's showing users warnings.
It also isn't outputting the same kind of object, which might be OK, but we should warn users that, for instance, the old example I had controlling digits will now break...

best, Tim

**Comment by tbates** [comment]
print also dumps the indices out into the console (rather than as a table)? and umx_print() doesn't recognise the object.

I would define a print S3 for this, not umx_print, which is a bit obscure for most users. I don't even think umx print is set up as an S3.

How about you try and make a file that just contains the two functions you want to alter, check them thoroughly, including adding more examples and  a test file for how it handles unexpected inout, and then email me those so I can replace the functions here?

**Comment by bwiernik** [comment]
Yes, I'll email you updated functions. I'm a bit confused about your other comments. The changes I made include a print S3 method (I didn't actually realize that umx_print() existed). Like most R print methods, it prints a nicely-formatted display to the console and returns the data.frame from the fit indices function invisibly.

**Comment by bwiernik** [comment]
I'll also make umx_print() more flexible to handle data.frames with multiple classes.

**Comment by tbates** [comment]
As you're working on this function, when you send the files, I will remove the old code, and commit a new umxFitIndices.R file so everything you're touching is in one place.

re printing

I misread `print.umxFitIndices` for some reason. Cool: Just stick with getting the S3 for your new class working. No need to touch `umx_print`.

For some reason for me, the print output from the updated fitindices was just a long labeled vector dumped out. Perhaps the class wasn't registered properly.

cheers,
t

**Comment by tbates** [comment]
FYI, I broke out the `umxFitIndices` function into its own file: `umx_fit_umxFitIndices.R` to make future updates from you easier

**Comment by bwiernik** [comment]
Superseded https://github.com/tbates/umx/pull/110

**Pull request closed without merging**
