### PR TITLE
Some code format stuff & bug fix

### PR DESCRIPTION
**Pull request by jpritikin**

### CODE REVIEW

**Comment by tbates** [comment]
I report the creation of latent variables by default, as these can come from typos (`umxRAM` makes a latent from anything not found in manifests)... probably best to stick with that (I have considered turning off all the narrative output, but shied away from it).

**Comment by jpritikin** [comment]
The problem is that `verbose=FALSE` does not disable all messages. I don't care what you decide to make the default as long as the behavior can be controlled.

**Comment by tbates** [comment]
`umx_set_silent(TRUE)`

Other's you might be interested in/want to control are:

* `umx_set_auto_run(FALSE)`
* `umx_set_auto_plot(FALSE)`

**Comment by tbates** [comment]
I wrapped the reporting of latents in `!umx_set_silent(silent=TRUE)` instead of verbose, so just turn silent on and then off again around whatever it is you're doing silently :-)

**Pull request merged**
